/** Canonical user-visible copy. Components must not introduce their own JSX text. */
const configuredAppName: unknown = import.meta.env.VITE_APP_NAME;
const defaultAppName =
  typeof configuredAppName === 'string' && configuredAppName.trim()
    ? configuredAppName.trim()
    : 'Lab Fish DB';
let activeAppName = defaultAppName;

export function setAppName(value: string): void {
  if (value.trim() !== '') activeAppName = value.trim();
}

export const strings = {
  get appName() {
    return activeAppName;
  },
  breedSoon: 'Breed soon',
  upcomingBreedingEmpty: (months: number) => `No line is older than ${String(months)} months.`,
  newGenerationPreview: (positive: number, generation: number) =>
    `IDed number will reset to ${String(positive)}; generation ${String(generation)} → ${String(generation + 1)}; status → Current.`,
  versionConflict: (user: string, time: string) =>
    `This line was changed by ${user} at ${time}. Reload to see the changes, then try again.`,
  closeConfirm: (line: string) => `${line} will move to Closed lines. You can reopen it later.`,
  mirrorFailed:
    'The Dropbox copy could not be updated. The database is fine; Admin has been notified.',
  dashboard: 'Dashboard',
  lines: 'Lines',
  newLine: 'New Line',
  search: 'Search',
  settings: 'Settings',
  continue: 'Continue',
  cancel: 'Cancel',
  confirm: 'Confirm',
  close: 'Close',
  loading: 'Loading',
  empty: 'Nothing to show yet.',
  placeholder: 'This page will be available soon.',
  current: 'Current',
  breeding: 'Breeding',
  closed: 'Closed',
  status: 'Status',
  styleGuide: 'Style guide',
  save: 'Save',
  toastClose: 'Dismiss notification',
  noUsers: 'No active users are available.',
  requestFailed: 'Something went wrong. Please try again.',
  idedNumber: 'IDed number',
  dismissIcon: '×',
  settingsIcon: '⚙',
  dropdownIcon: '▾',
  checkIcon: '✓',
  linesViewActive: 'Active',
  linesViewAll: 'All',
  line: 'Line',
  gene: 'Gene',
  phenotypes: 'Phenotype(s)',
  dob: 'DOB',
  idMethod: 'ID Method',
  lastIdDate: 'Last ID Date',
  cryopreserved: 'Cryopreserved',
  references: 'Reference(s)',
  yes: 'Yes',
  no: 'No',
  emptyValue: '—',
  breedSoonIcon: '⚠',
  referenceMissingLink: 'Missing link',
  referenceMissingIcon: '┄',
  moreReferences: (count: number) => `+${String(count)}`,
  linesOpenHint: 'Click a line to open its details.',
  openLineDetails: (name: string) => `Open details of ${name}`,
  linesEmpty: 'No lines match the current view.',
  linesNoMatch: 'No lines match the current filters. Try clearing a filter or the search.',
  ageMonths: (months: number) => `${String(months)} mo`,
  searchLabel: 'Search lines',
  searchPlaceholder: 'Name, gene, phenotype, or notes',
  // Header search (T-026)
  headerSearchPlaceholder: 'Search lines',
  headerSearchKey: '/',
  filterIdMethod: 'ID Method',
  filterIdMethodAny: 'Any ID Method',
  filterCryopreserved: 'Cryopreserved',
  filterCryopreservedAny: 'Any',
  filters: 'Filters',
  filterUpcomingBreeding: 'Upcoming breeding',
  filterBreedSoonOnly: 'Breed soon only',
  idMethodNone: 'None',
  idMethodTails: 'Tails',
  idMethodPcr: 'PCR',
  idMethodPcrSequence: 'PCR + Sequence',
  idMethodFluorescence: 'Fluorescence',
  idMethodCustom: 'Custom',
  columnsToggle: 'Columns',
  columnLastUpdate: 'Last Update',
  columnAgeMonths: 'Age (months)',
  columnNotes: 'Notes',
  exportCsv: 'Export CSV',
  activeLines: 'Active lines',
  closedLines: 'Closed',
  unreadMessages: 'Unread messages',
  upcomingBreeding: 'Upcoming Breeding',
  currentlyBreeding: 'Currently Breeding',
  recentActivity: 'Recent Activity',
  missingDob: 'Missing DOB',
  lineName: 'Line',
  days: 'Days',
  ageMonthsLabel: 'Age (months)',
  metadataSeparator: ' · ',
  statusSeparator: ' · ',
  openLine: 'Details',
  startBreeding: 'Start Breeding',
  updateGenotyping: 'Update Genotyping Record',
  seeActiveLines: 'See Active Lines',
  seeAllLines: 'See All Lines',
  addNewLine: 'Add New Line',
  showMore: 'Show more',
  showLess: 'Show less',
  labChat: 'Lab Chat',
  labChatPlaceholder: 'Lab-wide messages will appear here.',
  dashboardLoadError: 'Dashboard could not be loaded. Try again.',
  activityLoadError: 'More activity could not be loaded. Try again.',
  dashboardRetry: 'Retry',
  noBreedingLines: 'No lines are currently being bred.',
  noMissingDob: 'No active lines are missing a DOB.',
  noRecentActivity: 'No activity has been recorded yet.',
  noUnreadMessages: 'No unread messages.',
  ageInDays: (value: number) => `${String(value)} day${value === 1 ? '' : 's'}`,
  activityBy: (user: string, when: string) => `${user} · ${when}`,
  relativeLessThanMinute: '< 1 min ago',
  relativeMinutes: (value: number) => `${String(value)} min ago`,
  relativeHours: (value: number) => `${String(value)} h ago`,
  relativeDays: (value: number) => `${String(value)} d ago`,
  age: 'Age',
  currentIdMethod: 'Current ID method',
  breedingSince: 'Breeding since',
  closedOn: 'Closed on',
  closedReasonLabel: 'Closed reason',
  created: 'Created',
  moreAttributes: 'More attributes',
  edit: 'Edit',
  changeActivity: 'Change Activity',
  comingSoon: 'Coming soon',
  lineNotFound: 'This line does not exist. Go back to the line list and try again.',
  backToLines: 'Back to Lines',
  sectionSummary: 'Summary',
  sectionIdProtocols: 'ID Protocols',
  sectionCryopreservation: 'Cryopreservation',
  sectionActivity: 'Activity',
  chat: 'Chat',
  history: 'History',
  jumpIdProtocols: 'ID',
  jumpCryo: 'Cryo',
  jumpReferences: 'Refs',
  cryoSummaryCount: (records: number, straws: number) =>
    `${String(records)} record${records === 1 ? '' : 's'}, ${String(straws)} straw${straws === 1 ? '' : 's'}`,
  primerForward: 'Forward primer',
  primerReverse: 'Reverse primer',
  annealingTemperature: 'Annealing temperature',
  cyclesLabel: 'Cycles',
  expectedBandSize: 'Expected band size',
  sequencingPrimer: 'Sequencing primer',
  guideSequence: 'Guide sequence',
  expectedMutation: 'Expected mutation',
  sequenceResults: 'Sequence results',
  fluorophoreLabel: 'Fluorophore',
  screeningDay: 'Screening day',
  descriptionLabel: 'Description',
  customFields: 'Custom fields',
  daysPostFertilisation: (days: string) => `${days} dpf`,
  copy: 'Copy',
  copyAria: (label: string) => `Copy ${label}`,
  copiedToClipboard: 'Copied to clipboard',
  imagesHeading: 'Images',
  noImageYet: 'No image yet.',
  latestImage: 'Latest image',
  previousImages: (count: number) => `Other images (${String(count)})`,
  viewImage: (name: string) => `View image: ${name}`,
  closeImage: 'Close image',
  closeIcon: '×',
  imageFallbackName: 'Image',
  openFile: 'Open',
  cryoDate: 'Date',
  cryoPlace: 'Place',
  cryoBox: 'Box',
  cryoIds: 'IDs',
  detailsUnknown: 'Details unknown',
  cryoHeader: (records: number, straws: number) =>
    `Cryopreserved: Yes (${records === 1 ? '1 record' : `${String(records)} records`}, ${straws === 1 ? '1 straw' : `${String(straws)} straws`})`,
  cryoNone: 'Cryopreserved: No',
  referenceKindLink: 'Link',
  referenceKindPdf: 'PDF',
  referenceKindImage: 'Image',
  referenceKindFile: 'File',
  referenceNote: 'Note',
  generationLabel: 'Generation',
  generationHeader: (generation: number, dob: string, isCurrent: boolean) =>
    `Generation ${String(generation)} · DOB ${dob}${isCurrent ? ' · Current' : ''}`,
  genotyping: 'Genotyping',
  genotypingWithMethod: (method: string) => `Genotyping (${method})`,
  positiveTotal: (positive: number, total: number) =>
    `+${String(positive)} positive → total ${String(total)}`,
  screenedCount: (count: number) => `${String(count)} screened`,
  newGenerationRecord: (dob: string) => `New generation (DOB ${dob})`,
  versionLabel: (versionNo: number) => `v${String(versionNo)}`,
  showChanges: 'Show changes',
  hideChanges: 'Hide changes',
  diffField: 'Field',
  diffBefore: 'Before',
  diffAfter: 'After',
  noFieldChanges: 'No field changes were recorded for this version.',
  restoreVersion: 'Restore this version (Admin only)',
  // New Line form (T-011)
  newLineTitle: 'New Line',
  newLineProgress: 'Sections',
  sectionIdentity: 'Identity',
  sectionGeneration: 'Generation',
  sectionIdMethod: 'ID Method',
  sectionReferences: 'References',
  sectionToggle: (section: string, expanded: boolean) =>
    `${expanded ? 'Collapse' : 'Expand'} ${section}`,
  warningPrefix: 'Warning:',
  requiredNote: '* is required.',
  fieldLineName: 'Line name',
  fieldGene: 'Gene',
  fieldNotes: 'Notes',
  fieldPhenotypes: 'Phenotype(s)',
  phenotypeHint: 'Type a phenotype and press Enter to add it.',
  phenotypeAdd: 'Add',
  phenotypeRemove: (value: string) => `Remove phenotype ${value}`,
  phenotypeList: 'Added phenotypes',
  attributeKey: 'Attribute name',
  attributeValue: 'Value',
  attributeAdd: '+ Add attribute',
  attributeRemove: (row: number) => `Remove attribute ${String(row)}`,
  attributesHint: 'Optional extra facts about this line, for example Source.',
  fieldDob: 'Date of birth',
  dobToday: 'Today',
  fieldStatus: 'Status',
  fieldIdedNumber: 'IDed number',
  idMethodType: 'ID method',
  protocolLabel: 'Name',
  protocolLabelHint: 'Optional. Leave empty to use the method name.',
  protocolHeading: (position: number) => `ID protocol ${String(position)}`,
  protocolAdd: '+ Add another protocol',
  protocolRemove: (position: number) => `Remove ID protocol ${String(position)}`,
  protocolNotes: 'Protocol notes',
  primerFName: 'Forward primer name',
  primerFSequence: 'Forward primer sequence',
  primerRName: 'Reverse primer name',
  primerRSequence: 'Reverse primer sequence',
  annealingLabel: 'Annealing temperature (°C)',
  expectedBandLabel: 'Expected band size (bp)',
  cyclesFieldLabel: 'Cycles',
  sequencingPrimerField: 'Primer for sequencing',
  guideSequenceField: 'Guide sequence (CRISPR)',
  expectedMutationField: 'Expected mutation',
  sequenceResultLinks: 'Sequence result links',
  sequenceResultLinksHint: 'One link per line.',
  fluorophoreField: 'Fluorophore',
  fluorophoreChoose: 'Choose a fluorophore',
  screeningDayField: 'Screening day (dpf, 0–7)',
  screeningDayHint: 'A day or a range, for example 2 or 1-2.',
  descriptionField: 'Short description',
  customItemName: 'Field name',
  customItemValue: 'Value',
  customItemAdd: '+ Add field',
  customItemRemove: (row: number) => `Remove field ${String(row)}`,
  protocolNoFields: 'Only notes are recorded for this method.',
  cryoNotCryopreserved: 'Not cryopreserved',
  cryoAddFirst: 'Add first record',
  cryoChoice: 'Cryopreservation',
  cryoDateField: 'Cryopreservation date',
  cryoPlaceField: 'Place',
  cryoPlaceChoose: 'Choose a place',
  cryoBoxField: 'Box name',
  cryoIdStartField: 'First cryo ID',
  cryoIdEndField: 'Last cryo ID',
  cryoCountField: 'Count',
  cryoCountHint: 'Filled in from the ID range when left empty.',
  cryoDetailsUnknownField: 'Details unknown',
  cryoNotesField: 'Cryopreservation notes',
  referenceTitle: 'Title',
  referenceUrl: 'Link (http:// or https://)',
  referenceAdd: '+ Add reference',
  referenceRemove: (row: number) => `Remove reference ${String(row)}`,
  referencesHint: 'Links only for now. File uploads arrive later.',
  formCancel: 'Cancel',
  formSave: 'Save',
  formSaveAnother: 'Save and add another',
  formSaving: 'Saving…',
  formErrorSummary: (count: number) =>
    `${count === 1 ? '1 field needs' : `${String(count)} fields need`} attention. Fix ${count === 1 ? 'it' : 'them'} and save again.`,
  formErrorGo: 'Go to the first problem',
  formSaveFailed: 'The line could not be saved. Check your connection and try again.',
  nameChecking: 'Checking the name…',
  nameAvailable: 'This name is available.',
  nameOpenExisting: 'Open the existing line',
  unsavedTitle: 'Discard this new line?',
  unsavedBody: 'Nothing has been saved yet. Leaving now discards what you typed.',
  unsavedDiscard: 'Discard',
  unsavedKeep: 'Keep editing',
  lineCreated: (name: string) => `Line ${name} was created.`,
  lineCreatedOpen: 'Open the new line',
  lineCreatedFlash: (name: string) => `Line ${name} was created (version 1).`,
  attributionChoose: 'Lab member',
  attributionContinue: 'Continue',
  loadingForm: 'Loading the form',
  // Edit line (T-012)
  editTitle: (name: string) => `Edit ${name}`,
  editReason: 'Reason / note (optional)',
  editReasonHint: 'Shown in History next to this change.',
  editSaveFailed: 'The changes could not be saved. Check your connection and try again.',
  editDiscardTitle: 'Discard your changes?',
  editDiscardBody: 'Nothing has been saved yet. Closing now discards what you changed.',
  dobChangeWarning: 'Changing the date of birth affects Upcoming Breeding.',
  reload: 'Reload',
  lineUpdated: (version: number) => `Line updated (version ${String(version)}).`,
  lineUnchanged: 'No changes to save.',
  restoreTitle: (versionNo: number) => `Restore version ${String(versionNo)}?`,
  restoreIntro:
    'This puts back the name, gene, DOB, notes, phenotypes and More attributes of that version as a new version. Nothing is deleted.',
  restoreNoDifference:
    'Nothing to restore: the name, gene, DOB, notes, phenotypes and More attributes of that version are the same as now. A restore does not undo breeding, genotyping, ID method or cryopreservation changes (for example used vials: undo a use from the Cryopreservation section).',
  restoreConfirm: 'Restore',
  restoreLoadFailed: 'The changes of this version could not be loaded. Try again.',
  restoreFailed: 'The version could not be restored. Check your connection and try again.',
  restoreDone: (versionNo: number, version: number) =>
    `Restored the content of version ${String(versionNo)} (new version ${String(version)}).`,
  degreesCelsius: (value: number) => `${String(value)} °C`,
  // Export (T-019)
  exportMenu: 'Export',
  exportPdf: 'Export as PDF',
  generatedAt: 'Generated',
  // Change Activity (T-013)
  activityStartBreeding: 'Start Breeding',
  activityGenotyping: 'Update Genotyping Record',
  activityClose: 'Close This Line',
  activityReopen: 'Reopen This Line',
  activityCryo: 'Update Cryopreservation Info',
  activityIdMethod: 'Update ID Method',
  activityEditDetails: 'Edit Details',
  activityDisabledBreedingActive: 'This line is already breeding.',
  activityDisabledAlreadyClosed: 'This line is already closed.',
  activityDisabledNotClosed: 'Only a closed line can be reopened.',
  activityDisabledGuest: 'Guests cannot change line data. Sign in with your own account.',
  startBreedingTitle: (name: string) => `Start breeding: ${name}`,
  crossDate: 'Cross date',
  activityNote: 'Note (optional)',
  activityNoteHint: 'Shown in History next to this change.',
  start: 'Start',
  genotypingTitle: (name: string) => `Update genotyping record: ${name}`,
  genotypingDate: 'Genotyping date',
  genotypingProtocol: 'ID method used',
  genotypingProtocolNone: 'Not recorded',
  positiveNumber: 'Positive number',
  totalScreened: 'Total screened (optional)',
  generationChoiceLegend: 'Which generation is this?',
  generationSame: 'Add to the current generation',
  generationNew: 'This is a new generation',
  newDobField: 'New DOB',
  newDobHintBreeding:
    'Filled in from the breeding cross date; change it if the fish were born on another day.',
  newDobHintToday: 'Filled in with today; change it to the real date of birth.',
  sameGenerationPreview: (positive: number, total: number) =>
    `IDed number will become ${String(total)} (+${String(positive)}); generation and DOB stay the same.`,
  genotypingSave: 'Save record',
  closeTitle: (name: string) => `Close ${name}?`,
  closeReason: 'Reason (optional)',
  closeReasonHint: 'For example: line lost, no longer needed.',
  closeSubmit: 'Close line',
  reopenTitle: (name: string) => `Reopen ${name}?`,
  reopenBody: (name: string) => `${name} will move back to Current lines.`,
  reopenConfirm: 'Reopen line',
  activitySaving: 'Saving…',
  activityFailed: 'The change could not be saved. Check your connection and try again.',
  activityDone: (label: string, version: number) => `${label} (version ${String(version)}).`,
  activityDoneBreeding: 'Breeding started',
  activityDoneGenotyping: 'Genotyping record saved',
  activityDoneClosed: 'Line closed',
  activityDoneReopened: 'Line reopened',
  timelineBreedingStarted: 'Breeding started',
  timelineClosed: 'Line closed',
  timelineReopened: 'Line reopened',
  // ID protocols (T-014)
  protocolAddButton: '+ Add ID method',
  protocolAddTitle: 'Add ID method',
  protocolEditTitle: (label: string) => `Edit ID method: ${label}`,
  protocolAddSubmit: 'Add ID method',
  protocolMakeCurrent: 'Also a current ID method',
  protocolMakeCurrentHint: 'A line can have several current ID methods.',
  protocolTypeFixed:
    'The type of an ID method cannot be changed. Add a new one and remove this one instead.',
  protocolImageLater: 'Add gel or other images from the ID method card after saving.',
  protocolActionEdit: 'Edit',
  protocolSetCurrent: 'Mark as current',
  protocolUnsetCurrent: 'Remove from current',
  protocolMoveUp: 'Move up',
  protocolMoveDown: 'Move down',
  protocolRemoveAction: 'Remove',
  protocolRemoveTitle: (label: string) => `Remove ID method: ${label}?`,
  protocolRemoveBody: 'It will be hidden from this line. The Admin can bring it back.',
  protocolRemoveCurrent:
    'This is the only current ID method. The line will have no current ID method afterwards.',
  protocolRemoveSubmit: 'Remove ID method',
  protocolDoneAdded: 'ID method added',
  protocolDoneUpdated: 'ID method updated',
  protocolDoneRemoved: 'ID method removed',
  protocolDoneCurrent: 'Current ID methods changed',
  protocolDoneMoved: 'ID methods reordered',
  protocolMethodCleared: 'The line now has no current ID method.',
  protocolActionsLabel: (label: string) => `Actions for ${label}`,
  // Chat (T-017)
  chatEmpty: 'No messages yet. Start the conversation.',
  chatLoadFailed: 'Chat could not be loaded. Try again.',
  chatSendFailed: 'Message could not be sent. Check your connection and try again.',
  chatComposerLabel: 'Write a message',
  chatMentionHint: '@Name notifies a person, @all everyone',
  chatSendShortcutHint: 'Shift+Enter sends the message. Enter starts a new line.',
  chatSend: 'Send',
  chatRequestOptional: 'Request (optional)',
  chatNoRequest: 'No request',
  chatRequestOpen: 'Open request',
  chatRequestDone: 'Done',
  chatMarkDone: 'Mark done',
  chatReopen: 'Reopen',
  chatLoadEarlier: 'Load earlier messages',
  chatRead: 'Mark read',
  chatUnread: 'Mark unread',
  chatReadBy: (names: string) => `Read by ${names}`,
  chatEdit: 'Edit',
  chatDelete: 'Remove',
  chatSave: 'Save',
  chatCancelEdit: 'Cancel',
  chatEdited: 'edited',
  chatRemoved: 'Message removed.',
  chatEditedTime: 'Edit or remove available for 15 minutes after posting.',
  chatGuestNote: 'Guests can read messages but cannot write them.',
  chatRequestCount: (count: number) => `${String(count)} open request${count === 1 ? '' : 's'}`,
  chatOpenRequests: 'Open requests',
  chatNoOpenRequests: 'There are no open requests.',
  chatOpenRequest: 'Open request',
  chatNoUnreadMessages: 'There are no unread messages.',
  chatMarkAllRead: 'Mark all read',
  chatOpenChat: 'Open chat',
  chatUnreadBadge: (count: number) =>
    `${String(count)} unread chat message${count === 1 ? '' : 's'}`,
  chatRequestStatusSeparator: ' · ',
  // Dashboard greeting
  helloUser: (name: string) => `Hello, ${name}`,
  helloGuestHint: 'Guests can read but cannot change line data. Sign in with your own account.',
  pickLineLabel: 'Line',
  pickLineContinue: 'Continue',
  // Cryopreservation records (T-015)
  cryoAddButton: '+ Add record',
  cryoAddTitle: 'Add cryopreservation record',
  cryoEditTitle: 'Edit cryopreservation record',
  cryoAddSubmit: 'Add record',
  cryoPlaceOther: 'Other…',
  cryoPlaceOtherField: 'Place (other)',
  cryoNextFree: (id: string) => `Next free ID: ${id}`,
  cryoNextFreeHint:
    'Suggested from the highest ID used by any line. Change it if the straws use other IDs.',
  cryoCountFromRange: (count: number) => `Count: ${String(count)} (from the ID range)`,
  cryoActionEdit: 'Edit',
  cryoActionRemove: 'Remove',
  cryoActionsLabel: 'Actions',
  cryoRemoveTitle: 'Remove this cryopreservation record?',
  cryoRemoveBody:
    'It will be hidden from this line. The line stays cryopreserved while another record remains.',
  cryoRemoveSubmit: 'Remove record',
  cryoDoneAdded: 'Cryopreservation record added',
  cryoDoneUpdated: 'Cryopreservation record updated',
  cryoDoneRemoved: 'Cryopreservation record removed',
  cryoModeLegend: 'What do you want to record?',
  cryoModeAdd: 'Add vials',
  cryoModeUse: 'Use vials',
  cryoUseTitle: 'Record used vials',
  cryoUseSubmit: 'Record use',
  cryoUseIds: 'Used vial IDs',
  cryoUseIdsHint: (range: string | null, firstIds: string) =>
    range !== null
      ? `Separate IDs with commas. A range works too: ${range}.`
      : firstIds === ''
        ? 'Separate IDs with commas. A range works too.'
        : `Separate IDs with commas, for example ${firstIds}.`,
  cryoUseAvailable: (text: string) => `Vials on this line: ${text}`,
  cryoUseNoVials: 'This line has no vials to use.',
  cryoUseDate: 'Date used',
  cryoUseNote: 'Purpose / note (optional)',
  cryoUseNoIdsTitle: 'Or, for a record without vial IDs',
  cryoUseRecord: 'Record',
  cryoUseRecordChoose: 'Choose a record',
  cryoUseQuantity: 'Number of vials used',
  cryoUseWarning: 'Used vials are taken off the list for good, and their IDs cannot be used again.',
  cryoDoneUsed: 'Vial use recorded',
  // Undo a vial use (T-028)
  cryoUndoAction: 'Undo…',
  cryoUndoFor: (what: string) => `Undo the use of ${what}`,
  cryoUndoTitle: 'Undo this vial use?',
  cryoUndoBody: (what: string, place: string | null) =>
    `${what} will go back into ${place === null ? 'its record' : `the record at ${place}`}. If that use emptied the record, the record comes back too. The use stays in the log as undone, and History shows your name.`,
  cryoUndoNoteLabel: 'Why is it undone? (optional)',
  cryoUndoSubmit: 'Undo use',
  cryoDoneUndone: 'Vial use undone',
  cryoPlaceOtherHint: 'A new place is saved, so you can pick it next time.',
  cryoUsedHeading: (count: number) => `Used vials (${String(count)})`,
  cryoUsedOn: 'Used',
  cryoUsedQuantity: (count: number) => `${String(count)} vials`,
  cryoUsedCount: (count: number) => `${String(count)} used`,
  cryoActionUse: 'Use vials',
  moreActionsIcon: '⋯',
  cryoActionsFor: (what: string) => `Actions for ${what}`,
  // Uploads and references (T-016)
  uploadChoose: 'Choose file',
  uploadTakePhoto: 'Take photo',
  uploadImage: 'Upload image',
  uploadAnotherImage: 'Upload another image',
  uploadProgress: (percent: number) => `Uploading… ${String(percent)}%`,
  uploadDone: 'Image uploaded',
  uploadFailed: 'The file could not be uploaded. Check your connection and try again.',
  uploadRemoveImage: 'Remove image',
  uploadRemoveDone: 'Image removed',
  uploadZoomIn: 'Zoom in',
  uploadZoomOut: 'Zoom out',
  uploadZoomFit: 'Fit to screen',
  gelImageField: 'Gel image (optional)',
  gelImageHint: 'JPG, PNG, WebP, HEIC or PDF, up to 15 MB. On a phone you can take a photo.',
  gelImageChosen: (name: string) => `Selected: ${name}`,
  gelImageRemove: 'Clear',
  gelImageUploading: 'Uploading the gel image…',
  referenceAddButton: '+ Add reference',
  referenceAddTitle: 'Add reference',
  referenceEditTitle: 'Edit reference',
  referenceAddSubmit: 'Add reference',
  referenceTitleField: 'Title',
  referenceUrlField: 'Link (https://…)',
  referenceUrlHint: 'A Dropbox share link or any web link. Or upload a file below.',
  referenceFileField: 'Or upload a file',
  referenceFileHint: 'PDF, DOCX or an image, up to 15 MB.',
  referenceFileKeep: (name: string) => `Current file: ${name}. Choose a file to replace it.`,
  referenceNoteField: 'Note (optional)',
  referenceActionsFor: (title: string) => `Actions for ${title}`,
  referenceActionEdit: 'Edit',
  referenceActionRemove: 'Remove',
  referenceRemoveTitle: (title: string) => `Remove reference: ${title}?`,
  referenceRemoveBody: 'It will be hidden from this line. The file stays stored.',
  referenceRemoveSubmit: 'Remove reference',
  referenceDoneAdded: 'Reference added',
  referenceDoneUpdated: 'Reference updated',
  referenceDoneRemoved: 'Reference removed',
  // Settings (T-018)
  settingsTitle: 'Settings',
  settingsAdminOnly: 'Settings are for Admins. Ask an Admin if you need a change.',
  settingsLoadFailed: 'Settings could not be loaded. Check your connection and reload.',
  settingsTabs: 'Settings sections',
  tabUsers: 'Users',
  tabLists: 'Lists',
  tabPreferences: 'Preferences',
  tabData: 'Data & Backup',
  tabImportReport: 'Import report',
  usersAddHeading: 'Add a user and send an invite',
  userNameField: 'Name',
  userRoleField: 'Role',
  roleMember: 'Member',
  roleGuest: 'Guest',
  roleAdmin: 'Admin',
  userAdd: 'Add user and create invite',
  userActive: 'Active',
  userInactive: 'Removed',
  userBuiltin: 'Built-in',
  userActionsFor: (name: string) => `Actions for ${name}`,
  userRename: 'Rename',
  userMakeMember: 'Make Member',
  userMakeAdmin: 'Make Admin',
  userDeactivate: 'Remove',
  userReactivate: 'Reactivate',
  userRenameTitle: (name: string) => `Rename ${name}`,
  userDeactivateTitle: (name: string) => `Remove ${name}?`,
  userDeactivateBody:
    'They are signed out at once and can no longer sign in. Everything they did stays in History, and an Admin can reactivate them later.',
  userDoneAdded: 'User added',
  userDoneChanged: 'User updated',
  listsPick: 'List',
  listKindLabels: {
    id_method_type: 'ID method templates',
    fluorophore: 'Fluorophores',
    cryo_place: 'Cryo places',
    request_type: 'Request types',
    attribute_key: 'Attribute names',
  },
  listFixedNote:
    'This list is fixed by the application: the forms offer these templates. It is shown for reference.',
  listAddField: 'New entry',
  listAdd: 'Add to list',
  listDisable: 'Disable',
  listEnable: 'Enable',
  listRename: 'Rename',
  listDisabledTag: 'Disabled',
  listRenameNote:
    'Renaming changes what pickers offer next; values already saved on lines keep the old text.',
  listEntryActionsFor: (value: string) => `Actions for ${value}`,
  listRenameTitle: (value: string) => `Rename "${value}"`,
  listDoneAdded: 'Entry added',
  listDoneChanged: 'Entry updated',
  prefThreshold: 'Upcoming Breeding threshold (months)',
  prefDatabaseName: 'Database name',
  prefDatabaseNameHint:
    'Shown in the app header and page title, and in the Dropbox copy and offline snapshot.',
  prefThresholdHint: 'A Current line this old or older appears under Upcoming Breeding.',
  prefAnnealing: 'Default annealing temperature (°C)',
  prefCycles: 'Default PCR cycles',
  prefDefaultsHint: 'Used when a new PCR protocol leaves these empty.',
  prefSave: 'Save preferences',
  prefDone: 'Preferences saved',
  dataExportHeading: 'Export',
  dataExportBody:
    'Export now copies everything to the lab Dropbox folder (the same copy that is kept up to date automatically). The ZIP holds the same files for download: fish-database.json (full line documents), lines.csv (the Line List "All" view), one CSV per table and snapshot.html. Removed items are included and marked.',
  dataExportNow: 'Export now',
  dataExportNowBusy: 'Exporting…',
  dataExportNowDone: (files: number) =>
    `Dropbox copy finished (${String(files)} file${files === 1 ? '' : 's'} changed)`,
  dataDownloadZip: 'Download ZIP',
  dataDownloadSnapshot: 'Download snapshot.html',
  dataMirrorHeading: 'Dropbox mirror',
  dataMirrorNone:
    'No Dropbox copy has run yet. Export and download the ZIP by hand until the first copy succeeds.',
  dataMirrorNotConnected:
    'This server has no Dropbox connection, so nothing is copied automatically. Ask the maintainer to add the Dropbox secrets (operations guide, section 3.1).',
  dataMirrorOk: (at: string) => `Last successful copy: ${at}`,
  dataMirrorError: (text: string) => `Last error: ${text}`,
  dataMirrorFolder: (path: string) =>
    `Dropbox folder: Apps/Fish-Database-Copy${path === '/' ? '' : path}`,
  dataMirrorTick: (at: string) => `The automatic check last ran: ${at}`,
  dataMirrorTickNone: 'The automatic check has not run yet.',
  dataMirrorPending: 'Changes are waiting: the next copy starts within a few minutes.',
  dataMirrorUpToDate: 'Everything is copied.',
  dataMirrorRuns: 'Recent copies',
  dataMirrorRunKind: { on_change: 'After a change', nightly: 'Nightly', manual: 'Export now' },
  dataMirrorRunOk: (files: number) => `OK, ${String(files)} file${files === 1 ? '' : 's'}`,
  dataMirrorRunFailed: (why: string) => `Failed: ${why}`,
  dataUsageHeading: 'Usage this month',
  dataUsageNone:
    'Not connected yet: this card needs a Cloudflare API token, which is added when the mirror is set up. See the operations guide for the free-tier limits.',
  deletedHeading: 'Deleted items',
  deletedIntro: 'Nothing is ever deleted: removed items are hidden here until you restore them.',
  deletedEmpty: 'No deleted items.',
  deletedType: {
    protocol: 'ID method',
    cryo: 'Cryo record',
    reference: 'Reference',
    attachment: 'Image',
    message: 'Chat message',
  },
  deletedRestore: 'Restore',
  deletedRestoreFor: (label: string) => `Restore ${label}`,
  deletedLabLine: 'Lab chat',
  deletedDone: 'Item restored',
  deletedNotRestorable: (why: string) => `Cannot be restored: ${why}`,
  importReportNone: 'No import report is stored.',
  readOnlyBanner:
    'Read-only: an Admin is restoring the database. You can look at everything, but nothing can be changed until this message is gone.',
  readOnlyHeading: 'Read-only mode',
  readOnlyBody:
    'Turn this on before restoring the database (operations guide, section 2.1): every change by anyone is refused until you turn it off. Export now still works.',
  readOnlyIsOn: 'Read-only mode is ON. Nobody can change data.',
  readOnlyIsOff: 'Read-only mode is off.',
  readOnlyTurnOn: 'Turn read-only mode on',
  readOnlyTurnOff: 'Turn read-only mode off',
  readOnlyDone: (enabled: boolean) => (enabled ? 'Read-only mode is on' : 'Read-only mode is off'),
  mirrorStaleBanner:
    'The Dropbox copy is out of date: the last export failed or none succeeded for 24 hours.',
  mirrorStaleBannerLink: 'Open Data & Backup',
  // Accounts (ADR-0005, T-027)
  signInTitle: 'Sign in',
  signInHelp: 'Use your name and your password. Ask an Admin for an invite link if you have none.',
  signInName: 'Your name',
  signInPassword: 'Password',
  signInButton: 'Sign in',
  signInBusy: 'Signing in…',
  signInInviteHint:
    'Your initial password only works through your invite link. Open the link you were sent.',
  signOut: 'Sign out',
  signedInAs: (name: string) => `Signed in as ${name}`,
  guestView: 'Guest view: read only',
  menuFor: (name: string) => `Account menu for ${name}`,
  changePassword: 'Change password',
  changePasswordTitle: 'Choose a new password',
  changePasswordForced: 'Your Admin gave you an initial password. Choose your own to continue.',
  passwordCurrent: 'Current password',
  passwordNew: 'New password (at least 8 characters)',
  passwordSave: 'Save password',
  passwordDone: 'Password changed',
  joinTitle: (name: string) => `Welcome, ${name}`,
  joinHelp: 'Enter the initial password your Admin gave you, then choose your own password.',
  joinInitial: 'Initial password',
  joinNew: 'New password (at least 8 characters)',
  joinButton: 'Set password and sign in',
  joinInvalid: 'This invite link is not valid any more. Ask an Admin for a new one.',
  guestEntering: 'Opening the guest view…',
  guestInvalid: 'This guest link is not valid any more. Ask a lab member for the current link.',
  shareGuestLink: 'Copy guest link',
  guestLinkCopied: 'Guest link copied. Anyone with it can read the database but not change it.',
  guestLinkHeading: 'Guest link',
  guestLinkBody:
    'Anyone with the guest link can read lines and protocols, without a password. They cannot change anything. Every lab member can copy the link from their account menu.',
  guestLinkRotate: 'Replace the guest link',
  guestLinkRotateTitle: 'Replace the guest link?',
  guestLinkRotateBody: 'The old link stops working and every guest is signed out at once.',
  guestLinkRotated: 'Guest link replaced. Copy the new link from the account menu.',
  userInitialPassword: 'Initial password (at least 8 characters)',
  userInviteTitle: (name: string) => `Invite for ${name}`,
  userInviteBody:
    'Send this link to the person. It works once and expires in 7 days. Give them the initial password through another channel (not in the same message).',
  userInviteCopy: 'Copy invite link',
  userInviteCopied: 'Invite link copied',
  userInviteNew: 'New invite…',
  // Removed users (T-030)
  userShowRemoved: (count: number) => `Show removed users (${String(count)})`,
  userHideRemoved: 'Hide removed users',
  userDelete: 'Delete permanently…',
  userDeleteTitle: (name: string) => `Delete ${name} from the list for good?`,
  userDeleteBody:
    'The entry disappears, so the same name can be invited again as a new person. This only works for someone who never appears in History (changes, messages, uploads); otherwise the entry stays under "Removed users".',
  userDeleteConfirm: 'Delete for good',
  userDoneDeleted: 'User deleted',
  userInviteNewTitle: (name: string) => `New invite for ${name}`,
  userInviteNewBody:
    'Choose a new initial password. The old password stops working and the person is signed out everywhere.',
  userInviteCreate: 'Create invite',
  userWaiting: 'Invite pending',
  userNoPassword: 'No password yet',
  loginExpired: 'You were signed out. Sign in again to continue.',
} as const;
